### ISSUE TITLE
How to output to files also output to console?

### ISSUE THREAD

**Issue by eyesspace** [nikhilbharadwaj005/pino-daily-rotate-file#1]
How to output to files also output to console?

**Comment by nikhilbharadwaj005** [comment]
Hi @YANGLEDUO1 ,

Updated the package with a new env variable as **PINO_TO_CONSOLE**

Go through the package readme file and reinstall the package with recent version.

Thanks

**Comment by eyesspace** [comment]
Thank you for your reply and one more question. How to output which line of code is output


句号先森
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nikhilbharadwaj005/pino-daily-rotate-file"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月20日(星期一) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nikhilbharadwaj005/pino-daily-rotate-file] How to output to files also output to console? (Issue #1)





 
Hi @YANGLEDUO1 ,
 
Updated the package with a new env variable as PINO_TO_CONSOLE
 
Go through the package readme file and reinstall the package with recent version.
 
Thanks

**Comment by nikhilbharadwaj005** [comment]
As of now, Nothing like that has been added to the package.

To see the line number in the log, it should be added in the log manually. 
If you want to log an error, then an error stack trace has the line number details.
